services:
  nyu-press-api:
    build: 
      context: ./nyu-press-api  
      dockerfile: Dockerfile
    image: 395362471827.dkr.ecr.us-east-1.amazonaws.com/nyu-press-api:latest

  nyu-press-reader:
    build: 
      context: ./nyu-press-reader  
      dockerfile: Dockerfile
    image: 395362471827.dkr.ecr.us-east-1.amazonaws.com/nyu-press-reader:latest

  nyu-press-go:
    build:
      context: ./nyu-press-go
      dockerfile: Dockerfile
    image: 395362471827.dkr.ecr.us-east-1.amazonaws.com/nyu-press-go:latest  
